### ISSUE TITLE
Please add Dockerfile to the project

### ISSUE THREAD

**Issue by rahulmr** [mamantoha/mongo-sinatra-admin#45]
Hello your project looks nice, could you please add Dockerfile to this project.
I know ruby it creates lot of issues while setting environment, it will be easy if docker file is there.

**Comment by mamantoha** [comment]
Hi there,

Thank you for reaching out. Unfortunately, I am not interested in implementing this feature as I have no experience with Docker. However, if someone is interested in contributing to this project by creating a pull request, it would be greatly appreciated.

**Comment by rahulmr** [comment]
@mamantoha Thanks for replying. Could you please let me know which Ruby version you used while developing? If I get some time I will create the Dockerfile and send a pull request.

**Comment by mamantoha** [comment]
@rahulmr latest Ruby version
